 
 
 /**
 * This module is in charge of obtaining an OAuth 2.0 access token, either from 
 * a provided code or from a provided refresh token, for a given user.
 * The module stores the access and refresh token in the global storage
 * storage.global.Airvantage_username_AirvantageAccessToken
 * storage.global.Airvantage_username_AirvantageRefreshToken
 * @module TokenManager
 */

var config = require("../config.js");
var util = require("../util.js");
var http = require("http");

/** 
 * Retrieve the access and refresh tokens of a given user from te global storage
 * This method can throw exceptions
 * @method getPersistedTokens
 * @param {String} username : the name of the user for who we need the corresponding tokens
 * @return {Object} {accessToken, refreshToken}
 */
function getPersistedTokens(clientId) {
  
  var accessToken = storage.global["Airvantage_" + clientId + "_AirvantageAccessToken"];
  var refreshToken = storage.global["Airvantage_" + clientId + "_AirvantageRefreshToken"];
  if (!accessToken || !refreshToken) {
    
    throw {
      "errorCode": "Missing_Access_Token",
      "errorDetail": "Could not find an access token or a refresh token for this clientId " + clientId
    };
  }
  
  return {
    "accessToken": accessToken,
    "refreshToken": refreshToken
  };
}



function getAccessTokenFromCredentials() {
    if (!config.username || !config.password) {
      throw {
        "errorCode": "Invalid_Configuration",
        "errorDetail": "username and password are not set in the configuration file"
      };
    }
	var params = {
      "username": config.username,
      "password": config.password,
      "grant_type": "password"
    };

    return this._getToken(params);
}

/**
 * Invoke Airvantage authorization API to obtain an access token
 * This method can throw exceptions
 * @method getAccessToken
 * @param {Object} params
 *	{String} params.state : the state that was generated by fitbt/config when issuing the auth request
 *	{String} params.code : the OAuth code returned buy Airvantage further to the auth request, to be exchanged for a
 *  an access token
 * @return {Object} the API response. You do not need it normally. Get the tokens using getPersistedTokens()
 */
function getAccessToken(params) {
  
  if (!params) {
    
    throw {
      "errorCode": "Invalid_Parameter",
      "errorDetail": "getAccessToken - params cannot be null or empty"
    };
  }
  
  var params = {

    "state": params.state,
    "code": params.code,
    "grant_type": "authorization_code",
    "redirect_uri": config.redirect_uri
  };
  
  return this._getToken(params);
}

/**
 * Invoke Airvantage authorization API to obtain an access token using a refresh token
 * This method can throw exceptions
 * @method getAccessToken
 * @param {String} username : the name of the user for who we need to obtain a new access token
 * @return {Object} the API response. You do not need it normally. Get the tokens using getPersistedTokens()
 */
function refreshAccessToken(clientId) {

  if (!clientId) {
    
    throw {
      "errorCode": "Invalid_Parameter",
      "errorDetail": "You need to pass a clientId to refresh the token"
    };
  };
  
  var refreshToken = getPersistedTokens(clientId).refreshToken;
  if(refreshToken){
    var refreshParams = {
      "grant_type": "refresh_token",
      "refresh_token": refreshToken
    };
    return this._getToken(refreshParams, clientId);    
  }else{
	  return getAccessTokenFromCredentials();
  }
}

function _getToken(params, clientId) {
  
  var requestObject = {  

    "url": config.accessTokenUrl,
    "method": "POST",
    "params": params,
    "headers": {
      "Authorization": "Basic " +  util.Base64.encode(config.client_id + ":" + config.client_secret),
      "Content-Type": "application/x-www-form-urlencoded"
    }
  };

  var response = http.request(requestObject);
  console.log("Received response " +  JSON.stringify(response));
  var responseBodyStr = response.body;
  var responseObj = null;
  if (response.status == "200") {

    if (response.headers["Content-Type"].indexOf("application/json") > -1) {
      
      responseObj = JSON.parse(responseBodyStr);
      
      // retrieve the clientId who owns this token using the persisted state-username mapping
      var clientId = clientId ? clientId : storage.global["Airvantage_state_" + params.state];
          console.log(">>>>>>>>>>>>>>>>>>>>>>>clientId = " + clientId);
      if (!clientId) {
       	/*throw {
          "errorCode": "Inconsistency_Error",
          "errorDetail": "Could not find clientId " + clientId + " in store to store the tokens"
        };*/
        clientId = config.client_id;
      }

      // clean-up the state
      storage.global["Airvantage_state_" + params.state] = null;
      
      // persist the received access and refresh tokens in the storage and associate them to the targeted user
      storage.global["Airvantage_" + clientId + "_AirvantageAccessToken"] = responseObj["access_token"];
      storage.global["Airvantage_" + clientId + "_AirvantageRefreshToken"] = responseObj["refresh_token"];
      return responseObj;
    }else {
      
      throw {
        "errorCode": "Unexpected_Response",
        "errorDetail": responseBodyStr
      }
    }    
  }else {
    
    var errorObj = "";
    try {
      
      errorObj = JSON.parse(response.body);
      errorObj = errorObj.errors;
    }catch(e) {
      errorObj = JSON.parse(response);
    };
    
    throw {
      
      "errorCode": "Authorization_Failed",
      "errorDetail": errorObj
    };
  }
}			